use_frameworks!

target 'LoadingView_Example' do
  pod 'LoadingView', :path => '../'

  target 'LoadingView_Tests' do
    inherit! :search_paths
    use_frameworks!
    pod 'Nimble', '~> 6.0.0'
  end
end
